const $=id=>document.getElementById(id), KEY='tgr-contagem-v1';
let registros=[],tipo='estoque',atual=null;
$('codigo').oninput=()=>{atual=null;$('produto').hidden=true;$('erro').textContent='';const codigo=$('codigo').value.trim(),p=PRODUTOS[codigo];$('previaNome').textContent=p?p.nome:codigo?'Digite o código completo para identificar o produto.':'';};
try{registros=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(registros))registros=[]}catch(e){$('aviso').textContent='Não foi possível recuperar o rascunho. Exporte a contagem antes de sair.'}
function persistir(){try{localStorage.setItem(KEY,JSON.stringify(registros));return true}catch(e){$('aviso').textContent='Não foi possível salvar neste aparelho. Baixe o CSV antes de fechar a página.';return false}}
function tela(id){['atividades','inicio','contar','salvar','coletas'].forEach(x=>$(x).hidden=x!==id);$('status').textContent=registros.length+' registros nesta contagem';window.scrollTo(0,0)}
function abrir(t){tipo=t;atual=null;$('titulo').textContent=t==='estoque'?'Contagem de estoque':'Contagem de avarias';$('codigo').value='';$('previaNome').textContent='';$('produto').hidden=true;$('erro').textContent='';$('aviso').textContent='';tela('contar');$('codigo').focus()}
$('busca').onsubmit=e=>{e.preventDefault();const codigo=$('codigo').value.trim();atual=PRODUTOS[codigo];$('produto').hidden=!atual;$('erro').textContent=atual?'':'Código não encontrado na base.';if(!atual)return;$('codExibido').textContent='CÓDIGO '+codigo;$('nome').textContent=atual.nome;[['emb','embalagem'],['porPalete','palete'],['porLastro','lastro']].forEach(([id,k])=>$(id).textContent=atual[k]>0?atual[k]:'Não informado');['palete','lastro','caixa'].forEach(id=>{$(id).value=0;$(id).disabled=id!=='caixa'&&!(atual[id]>0)});$('observacao').value='';if(!(atual.palete>0)||!(atual.lastro>0))$('erro').textContent='Conversões ausentes na base: conte em caixas ou utilize apenas o campo com conversão informada.';calcular()};
function calcular(){const total=['palete','lastro','caixa'].reduce((s,k)=>s+Number($(k).value||0)*(k==='caixa'?1:Number(atual?.[k]||0)),0);$('total').textContent=total.toLocaleString('pt-BR');return total}
['palete','lastro','caixa'].forEach(k=>$(k).oninput=calcular);
$('registro').onsubmit=e=>{e.preventDefault();if(!atual)return;const q=Object.fromEntries(['palete','lastro','caixa'].map(k=>[k,Number($(k).value)]));if(Object.values(q).some(v=>!Number.isSafeInteger(v)||v<0))return;const total=calcular();if(!Number.isSafeInteger(total))return;registros.push({id:Date.now()+'-'+Math.random().toString(36).slice(2),tipo,codigo:$('codigo').value.trim(),nome:atual.nome,...q,porPalete:atual.palete,porLastro:atual.lastro,total,observacao:$('observacao').value.trim(),data:new Date().toISOString()});const salvo=persistir();abrir(tipo);$('aviso').textContent=salvo?'Produto salvo. Pesquise o próximo código.':'Produto registrado em memória. Baixe o CSV antes de fechar: não foi possível salvar no aparelho.'};
function resumo(){tela('salvar');$('resumo').textContent=registros.length+' registros • Estoque: '+registros.filter(r=>r.tipo==='estoque').reduce((s,r)=>s+r.total,0).toLocaleString('pt-BR')+' caixas • Avarias: '+registros.filter(r=>r.tipo==='avarias').reduce((s,r)=>s+r.total,0).toLocaleString('pt-BR')+' caixas';$('lista').replaceChildren();registros.forEach(r=>{const div=document.createElement('div');div.className='linha';const title=document.createElement('strong');title.textContent=r.codigo+' • '+r.nome;const detail=document.createElement('p');detail.textContent=(r.tipo==='estoque'?'Estoque':'Avarias')+' • '+r.total+' caixas ('+r.palete+' paletes, '+r.lastro+' lastros, '+r.caixa+' caixas soltas)';const btn=document.createElement('button');btn.textContent=r.enviado?'Salvo no Google':'Excluir registro';btn.disabled=!!r.enviado;btn.onclick=()=>{if(confirm('Excluir este registro?')){registros=registros.filter(x=>x.id!==r.id);persistir();resumo()}};div.append(title,detail,btn);$('lista').append(div)});$('exportar').disabled=!registros.length}
function csv(v){let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function exportar(){if(!registros.length)return;const headers=['Responsável','Tipo','Código','Produto','Paletes','Lastros','Caixas soltas','Caixas por palete','Caixas por lastro','Total em caixas','Observação','Data e hora'];const rows=registros.map(r=>[$('responsavel').value.trim(),r.tipo,r.codigo,r.nome,r.palete,r.lastro,r.caixa,r.porPalete,r.porLastro,r.total,r.observacao,new Date(r.data).toLocaleString('pt-BR')]);const blob=new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(csv).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Contagem_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('aviso').textContent='Download solicitado. Confira o arquivo na pasta de downloads.'}
function limpar(){if(typeof envioPendente!=='undefined'&&envioPendente){alert('Aguarde o envio terminar.');return}if(!registros.length||confirm('Iniciar nova contagem apagará o rascunho deste aparelho. Já baixou o CSV?')){registros=[];persistir();tela('inicio')}}
tela('atividades');
