const RK='tgr-recebimento-v1';
let recebimento={id:crypto.randomUUID(),itens:[],dados:{},salvo:false},recebimentoEnvio=null;
try{const r=JSON.parse(localStorage.getItem(RK)||'null');if(r&&Array.isArray(r.itens))recebimento=r}catch{}
function guardarRecebimento(){try{localStorage.setItem(RK,JSON.stringify(recebimento))}catch{$('rcAviso').textContent='O rascunho não pôde ser guardado neste aparelho. Mantenha a página aberta até salvar no Google.'}}
function dataBahia(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function rcEtapa(etapa){$('rcColeta').hidden=etapa!==1;$('rcFinal').hidden=etapa!==2;$('rcImpressao').hidden=etapa!==3;rcLista()}
function rcProduto(){const p=PRODUTOS[$('rcCodigo').value.trim()];$('rcNome').textContent=p?p.nome:'Código não encontrado na base';['Palete','Lastro'].forEach(k=>{const input=$('rc'+k);input.disabled=!(p?.[k.toLowerCase()]>0);if(input.disabled)input.value=0});$('rcConversao').textContent=p?'Caixas por palete: '+(p.palete||'não informado')+' • Caixas por lastro: '+(p.lastro||'não informado'):'';rcTotal()}
function rcTotal(){const p=PRODUTOS[$('rcCodigo').value.trim()];const n=Number($('rcPalete').value||0)*(p?.palete||0)+Number($('rcLastro').value||0)*(p?.lastro||0)+Number($('rcCaixa').value||0);$('rcTotal').textContent=n.toLocaleString('pt-BR')+' caixas';return n}
function rcLista(){const list=$('rcLista');list.replaceChildren();recebimento.itens.forEach((r,i)=>{const div=document.createElement('div');div.className='linha';const p=document.createElement('p');p.textContent=r.codigo+' • '+r.nome+' • Validade: '+rcData(r.validade)+' • '+r.total+' caixas • '+r.fisicos+' paletes para etiquetar';const b=document.createElement('button');b.type='button';b.textContent='Excluir';b.disabled=recebimento.salvo||!!recebimentoEnvio;b.onclick=()=>{if(confirm('Excluir este produto da coleta?')){recebimento.itens.splice(i,1);guardarRecebimento();rcLista()}};div.append(p,b);list.append(div)});$('rcResumo').textContent=recebimento.itens.length+' lançamentos • '+recebimento.itens.reduce((s,r)=>s+r.total,0)+' caixas';$('rcImprimir').disabled=!recebimento.salvo;$('rcSalvar').disabled=recebimento.salvo||!!recebimentoEnvio}
function rcData(s){return s?s.split('-').reverse().join('/'):'—'}
$('rcCodigo').oninput=rcProduto;['rcPalete','rcLastro','rcCaixa'].forEach(k=>$(k).oninput=rcTotal);
$('rcItem').onsubmit=e=>{e.preventDefault();if(recebimento.salvo||recebimentoEnvio)return;const codigo=$('rcCodigo').value.trim(),p=PRODUTOS[codigo];if(!p){$('rcAviso').textContent='Informe um código válido.';return}const q=['Palete','Lastro','Caixa'].map(k=>Number($('rc'+k).value));const fisicos=Number($('rcFisicos').value),total=rcTotal();if(q.some(n=>!Number.isSafeInteger(n)||n<0)||!Number.isSafeInteger(total)||total<=0||!Number.isSafeInteger(fisicos)||fisicos<1||fisicos>1000){$('rcAviso').textContent='Confira as quantidades. Informe pelo menos um palete físico para etiquetar.';return}recebimento.itens.push({id:crypto.randomUUID(),codigo,nome:p.nome,palete:q[0],lastro:q[1],caixa:q[2],porPalete:p.palete||0,porLastro:p.lastro||0,total,validade:$('rcValidade').value,fisicos});guardarRecebimento();$('rcItem').reset();$('rcNome').textContent='';$('rcConversao').textContent='';$('rcAviso').textContent='Produto adicionado à coleta.';rcTotal();rcLista();$('rcCodigo').focus()};
const rcCampos=['Chapatex','Madeira','NF','Emissao','Origem','Carreta','Cavalo','Data','Hora','Turno','Conferente','Motorista','Lados'];
rcCampos.forEach(k=>{const el=$('rc'+k);if(recebimento.dados[k]!=null)el.value=recebimento.dados[k];el.addEventListener('input',()=>{if(!recebimento.salvo){recebimento.dados[k]=el.value;guardarRecebimento()}})});
if(!$('rcData').value)$('rcData').value=dataBahia();
$('rcFimColeta').onsubmit=e=>{e.preventDefault();if(!recebimento.itens.length){$('rcAviso').textContent='Adicione pelo menos um produto.';return}rcCampos.forEach(k=>recebimento.dados[k]=$('rc'+k).value);guardarRecebimento();rcEtapa(2)};
$('rcDados').onsubmit=e=>{e.preventDefault();rcCampos.forEach(k=>recebimento.dados[k]=$('rc'+k).value);guardarRecebimento();rcSalvar()};
function rcSalvar(){
 if(recebimentoEnvio||recebimento.salvo)return;
 if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(GOOGLE_SCRIPT_URL)){alert('Endereço do Apps Script não configurado.');return}
 if(location.protocol!=='https:'){alert('Abra o site publicado no GitHub para salvar.');return}
 const nonce=crypto.randomUUID(),frame=document.createElement('iframe'),form=document.createElement('form'),input=document.createElement('input');frame.name='rc_'+nonce;frame.hidden=true;form.hidden=true;form.method='POST';form.action=GOOGLE_SCRIPT_URL;form.target=frame.name;input.name='payload';input.value=JSON.stringify({acao:'recebimento',nonce,origin:location.origin,recebimento});form.append(input);document.body.append(frame,form);recebimentoEnvio={nonce,frame,form};rcBloquear(true);$('rcAviso').textContent='Salvando recebimento no Google…';form.submit();recebimentoEnvio.timer=setTimeout(()=>rcTerminar('Sem confirmação do Google. O rascunho foi mantido; tente novamente. O mesmo recebimento não será duplicado.'),60000);
}
function rcBloquear(b){$('rcCamposColeta').disabled=b||recebimento.salvo;$('rcCamposFinal').disabled=b||recebimento.salvo;rcLista()}
function rcTerminar(msg){if(recebimentoEnvio){clearTimeout(recebimentoEnvio.timer);recebimentoEnvio.frame.remove();recebimentoEnvio.form.remove();recebimentoEnvio=null}rcBloquear(false);$('rcAviso').textContent=msg}
window.addEventListener('message',e=>{if(!/^https:\/\/([\w-]+\.)*googleusercontent\.com$/.test(e.origin)&&e.origin!=='https://script.google.com')return;const d=e.data;if(!recebimentoEnvio||!d||d.tipo!=='tgr-recebimento'||d.nonce!==recebimentoEnvio.nonce)return;if(d.ok&&d.id===recebimento.id){recebimento.salvo=true;guardarRecebimento();rcTerminar('Recebimento confirmado na planilha. As etiquetas estão disponíveis.');rcEtapa(3)}else rcTerminar('Não foi possível salvar: '+(d.erro||'resposta incompleta'))});
function rcNovo(){if(recebimentoEnvio)return;if(!recebimento.salvo&&recebimento.itens.length&&!confirm('Descartar este rascunho e iniciar outro recebimento?'))return;recebimento={id:crypto.randomUUID(),itens:[],dados:{},salvo:false};$('rcItem').reset();$('rcFimColeta').reset();$('rcDados').reset();$('rcData').value=dataBahia();$('rcNome').textContent='';$('rcAviso').textContent='';guardarRecebimento();rcBloquear(false);rcEtapa(1)}
function rcEtiquetas(){let numero=0;return recebimento.itens.flatMap(r=>Array.from({length:r.fisicos},()=>{numero++;return Array.from({length:Number(recebimento.dados.Lados||3)},()=>({...r,numero}))}).flat())}
const rcEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rcPreview(){const etiquetas=rcEtiquetas();$('rcQuantidadeEtiquetas').textContent=etiquetas.length+' etiquetas • '+Math.ceil(etiquetas.length/3)+' folhas A4';return etiquetas}
function rcImprimir(){if(!recebimento.salvo)return;const etiquetas=rcPreview(),d=recebimento.dados;if(etiquetas.length>3000){alert('Lote muito grande. Divida o recebimento para impressão.');return}const w=window.open('','_blank');if(!w){alert('Permita a abertura da janela de impressão.');return}let pages='';for(let i=0;i<etiquetas.length;i+=3){pages+='<div class="folha">'+etiquetas.slice(i,i+3).map(r=>`<article class="etiqueta"><div class="codigo"><u>Código ${rcEscape(r.codigo)}</u><span>Nº ${r.numero}</span></div><div class="nome">${rcEscape(r.nome)}</div><div class="venc"><b>Venc:</b><strong>${rcData(r.validade)}</strong></div><div class="receb">Receb.: <b>${rcData(d.Data)}</b><span>NF: ${rcEscape(d.NF)}</span></div><div class="rodape">${[['Conferente',d.Conferente],['Turno',d.Turno],['Hora',d.Hora],['Qtde recebida (cx)',r.total],['Motorista',d.Motorista],['Origem',d.Origem],['Placa carreta',d.Carreta]].map(([k,v])=>'<div><b>'+rcEscape(k)+'</b><span>'+rcEscape(v)+'</span></div>').join('')}</div></article>`).join('')+'</div>'}w.document.write('<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Etiquetas de paletes</title><style>@page{size:A4 portrait;margin:8mm}*{box-sizing:border-box}body{margin:0;font-family:Arial;color:#000}.folha{height:280mm;display:flex;flex-direction:column;gap:4mm;break-after:page}.folha:last-child{break-after:auto}.etiqueta{height:90mm;border:1px solid #000;display:flex;flex-direction:column;overflow:hidden;break-inside:avoid}.codigo{padding:3mm 5mm;font-size:16pt;text-align:center;position:relative}.codigo span{position:absolute;right:4mm;font-size:13pt}.nome{text-align:center;font-size:19pt;padding:3mm 5mm;flex:1;overflow-wrap:anywhere}.venc{display:flex;align-items:center;justify-content:space-between;gap:3mm;background:#000;color:#fff;padding:3mm 4mm;print-color-adjust:exact;-webkit-print-color-adjust:exact}.venc b{font-size:22pt}.venc strong{font-size:42pt;white-space:nowrap}.receb{display:flex;gap:3mm;padding:3mm 4mm;font-size:15pt}.receb span{margin-left:auto}.rodape{display:grid;grid-template-columns:repeat(7,1fr);gap:2mm;padding:2mm 3mm;font-size:8pt;text-align:center}.rodape b{display:block;text-decoration:underline;margin-bottom:2mm}.rodape span{display:block;overflow-wrap:anywhere}.acoes{padding:15px}@media print{.acoes{display:none}}@media screen{body{background:#ddd}.folha{width:194mm;margin:15px auto;background:white}}</style></head><body><div class="acoes"><button onclick="window.print()">Imprimir etiquetas</button> Use A4, escala 100%, sem cabeçalhos/rodapés e com gráficos de fundo ativados.</div>'+pages+'</body></html>');w.document.close();w.focus();w.print()}
const rcEtapaOriginal=rcEtapa;rcEtapa=function(n){rcEtapaOriginal(n);if(n===3)rcPreview()};rcEtapa(recebimento.salvo?3:1);rcBloquear(false);
